spring:
  application:
    name: appointment-system
  datasource:
    url: jdbc:postgresql://localhost:5432/appointments
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      "[mail.smtp.starttls.enable]": true
      "[mail.smtp.stattls.required]": true