name: Continuous Integration with Github

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Docker Login
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Setup Java JDK
        uses: actions/setup-java@v3.9.0
        with:
          java-version: "21"
          distribution: "temurin"
          cache: "maven"

      - name: Check Maven and Java
        run: |
          mvn -v
          java -version

      - name: Build appointment Microservice Jar
        run: ./mvnw verify

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.18.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Check Docker and Docker Compose
        run: |
          docker --version
          docker-compose --version

      - name: Docker Compose Build
        working-directory: .
        run: docker-compose build

      - name: Push to Docker Hub Container Registry
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/appointment:0.0.1-SNAPSHOT ${{ secrets.DOCKER_USERNAME }}/appointment:${{github.run_id}}
          docker tag ${{ secrets.DOCKER_USERNAME }}/appointment:0.0.1-SNAPSHOT ${{ secrets.DOCKER_USERNAME }}/appointment:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/appointment:${{github.run_id}}
          docker push ${{ secrets.DOCKER_USERNAME }}/appointment:latest
